# 通用配置开始
spring:
  application:
    name: swagger-demo
  profiles:
    active: dev # 需要激活的配置文件，dev,test,pro
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  main:
    banner-mode: off
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    # 内容协商
    contentnegotiation:
      favor-parameter: true # 使用参数进行内容协商（默认是没有开启的） ,默认参数名：format
      parameter-name: type # 修改内容协商的参数名称
      media-types:
        yaml: text/yaml # 增加一种新的内容类型
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html

# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印SQL语句
    map-underscore-to-camel-case: true #开启驼峰命名
    cache-enabled: true  # 开启MyBatis二级缓存
  global-config:
    banner: off #关闭mybatisplus启动图标
  type-aliases-package: com.example.entity

# 通用配置结束

# 天气相关配置
weather:
  appId: 52732916
  appSecret: qdGN90PE
